### ISSUE TITLE
jqXHR.responseJSON is undefined

### ISSUE THREAD

**Issue by b-jerome** [roadster31/Tags#3]
Bonjour,

Je n'arrive pas à utiliser le module. Lorsque j'essaye de l'activé via le back-office le switch se remet en position désactivé automatiquement. Dans la console j'ai l'erreur jqXHR.responseJSON is undefined.

J'ai essayé de l'activé manuellement dans la base de donnée mais ça ne fonctionne pas non plus.

Version Thelia 2.3.5

**Comment by roadster31** [comment]
Je pense que le problème vient plutôt du navigateur que du module.  Merci d'essayer avec un autre navigateur.

**Comment by b-jerome** [comment]
J'ai cette erreur dans les logs 

AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Tags\\TagsQuery' not found in /local/modules/Tags/Tags.php:28

**Comment by roadster31** [comment]
Les caches ont été vidés ?

Quelle est la version de Thelia ?

**Comment by b-jerome** [comment]
Oui j'ai vidé les caches. Version Thelia 2.3.5

**Comment by b-jerome** [comment]
J'ai créer la table manuellement et commenté la ligne

`//TagsQuery::create()->findOne();`

Ça fonctionne. Il semble bien y avoir un soucis sur cette partie du module ?

**Comment by roadster31** [comment]
Oui, je pense qu'il manque un import. Merci d'avoir trouvé le problème, je vais le corriger.

**Comment by b-jerome** [comment]
De rien bonne continuation et merci pour ton travail :)

**Comment by roadster31** [comment]
Et voilà, il y avait déjà une PR sur le module que j'avais ommis de merger, désolé.
